<?php
if (!isset($_SESSION)) {
    session_start();
}
//Declaration des classes à inclure
include_once("../class/ConnectAdmin.php");
include_once("../class/Functions.php");
include_once("../class/utilisateur.php");
include_once("../class/structure.php");
include_once("../class/parametre.php");
include_once("../class/profil.php");
include_once("../class/userprofil.php");
include_once("../class/menuprofil.php");
include_once("../class/localite.php");
include_once("../class/principarle.php");
include_once("../class/notification.php");
include_once("../class/destinataire.php");
include_once("../class/annee.php");
include_once("../class/mois.php");
include_once("../class/personne.php");
include_once("../class/typepersonne.php");
include_once("../class/situationmatri.php");
include_once("../class/sexe.php");
include_once("../class/droitacces.php");
include_once("../class/civilite.php");
include_once("../class/etat.php");
include_once("../class/unite.php");
include_once("../class/titre.php");
include_once("../class/fichier.php");

include_once("../class/acteurs.php");
include_once("../class/acteurs.php");
include_once("../class/bureauechange.php");
include_once("../class/elementscp.php");
include_once("../class/actionnonlivraison.php");
include_once("../class/expedition.php");
include_once("../class/voieacheminement.php");
include_once("../class/pays.php");
include_once("../class/scp.php");




//include_once("../class/demandetravaux.php");
//include_once("../class/rubriques.php");
//include_once("../class/operationfinanciere.php");
//include_once("../class/typepiece.php");
//include_once("../class/rubriqueassocie.php");
//include_once("../class/typeoperationfinanciere.php");
//include_once("../class/compte.php");
//include_once("../class/domaineactivite.php");
//include_once("../class/provenance.php");
//
//include_once("../class/fonction.php");
//include_once("../class/personne.php");
//include_once("../class/situationmatri.php");
//include_once("../class/sexe.php");
//include_once("../class/presence.php");
//include_once("../class/absence.php");
//include_once("../class/previsiontache.php");
//include_once("../class/objectifsjr.php");
//include_once("../class/suivitache.php");
//include_once("../class/rapports.php");
//include_once("../class/contrat.php");
//include_once("../class/echeancier.php");
//include_once("../class/suiviprime.php");
//include_once("../class/priorite.php");
//include_once("../class/detailsobjectif.php");
//include_once("../class/typepersonne.php");
//include_once("../class/titre.php");
//include_once("../class/anneeacademique.php");
//include_once("../class/programme.php");
//include_once("../class/detailsprogram.php");
//include_once("../class/planning.php");
//include_once("../class/niveauprogram.php");
//include_once("../class/sourceoperation.php");
//include_once("../class/droitacces.php");
//include_once("../class/element.php");
//
//include_once("../class/typepunition.php");
//include_once("../class/typenote.php");
//include_once("../class/punition.php");
//include_once("../class/notes.php");
//include_once("../class/typefamille.php");
//include_once("../class/typepaiement.php");
//include_once("../class/typereglement.php");
//include_once("../class/famille.php");
//include_once("../class/modereglement.php");
//include_once("../class/detailsmodereglement.php");
//include_once("../class/banque.php");
//include_once("../class/acteurcommercial.php");
//include_once("../class/civilite.php");
//include_once("../class/etat.php");
//include_once("../class/banqueacteur.php");
//include_once("../class/typeunite.php");
//include_once("../class/unite.php");
//include_once("../class/promotion.php");
//include_once("../class/elementcommercial.php");
//include_once("../class/typeelementcommercial.php");
//include_once("../class/chantier.php");
//include_once("../class/fournisseurelement.php");
//include_once("../class/detailsouvrage.php");
//include_once("../class/executantdt.php");
//include_once("../class/conditionreglement.php");
//include_once("../class/depot.php");
//include_once("../class/taxe.php");
//include_once("../class/representant.php");
//include_once("../class/devis.php");
//include_once("../class/mouvement.php");
//include_once("../class/detailsdevis.php");
//include_once("../class/paramcomptelt.php");
//include_once("../class/ecriture.php");
//include_once("../class/journal.php");
//include_once("../class/chequeoperation.php");


?>